com.miHoYo.Yuanshen=40,45,48
com.miHoYo.ys.mi=40,45,48
com.miHoYo.ys.bilibili=40,45,48
com.miHoYo.GenshinImpact=40,45,48
com.kurogame.mingchao=40,45,48
com.miHoYo.hkrpg=40,45,48
com.miHoYo.hkrpg.bilibili=40,45,48
com.HoYoverse.hkrpgoversea=40,45,48
com.dw.h5yvzr.yt=40,45,48
com.pwrd.hotta.laohu=40,45,48
com.hottagames.hotta.bilibili=40,45,48
com.hottagames.hotta.mi=40,45,48
com.epicgames.fortnite=40,45,48